"""Custom exceptions for Priqualis."""

class PriqualisError(Exception):
    """Base exception for all Priqualis errors."""

# ETL
class ETLError(PriqualisError): ...
class SchemaValidationError(ETLError): ...
class ImportError(ETLError): ...
class PIIMaskingError(ETLError): ...

# Rule Engine
class RuleEngineError(PriqualisError): ...
class RuleParseError(RuleEngineError): ...
class RuleExecutionError(RuleEngineError): ...
class InvalidRuleStateError(RuleEngineError): ...

# Search
class SearchError(PriqualisError): ...
class IndexNotFoundError(SearchError): ...
class EmbeddingError(SearchError): ...
class VectorStoreError(SearchError): ...

# AutoFix
class AutoFixError(PriqualisError): ...
class PatchGenerationError(AutoFixError): ...
class PatchApplicationError(AutoFixError): ...